# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-12 20:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('Gym', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Business.Instructor'),
        ),
        migrations.AddField(
            model_name='class',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym.Location'),
        ),
    ]
