# Generated by Django 4.1.7 on 2023-02-26 11:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gym', '0002_equipment'),
        ('Business', '0003_alter_plan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Business.instructor'),
        ),
        migrations.AlterField(
            model_name='class',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym.location'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym.equipment'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym.location'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym.location')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Business.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
