# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-07 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0006_auto_20230506_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='is_free_trial',
        ),
    ]
