# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-07 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20230506_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
