# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-07 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_user_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
