# Generated by Django 4.1.7 on 2023-02-26 10:08

import django.core.validators
from django.db import migrations, models
import localflavor.us.models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('street', models.CharField(max_length=200, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Invalid postal code')])),
            ],
        ),
    ]
