# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-26 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0002_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name=b'manufacturer',
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Gym.Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
