# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-07 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0003_auto_20230326_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='location',
        ),
    ]
